### ISSUE TITLE
body undefined in appHandler

### ISSUE THREAD

**Issue by robclewley** [deleteman/tardis-project-client#1]
I'm excited to try out your game as a tutorial to get me started in using node for a text-based browser game, as I am new to working with node. I have a fresh install of the dependencies that meet the stated version requirements (May 2020), and running `node index.js` gives me

```
/tardis-project-client/lib/appHandler.js:13
			if(body.error) {
			        ^

TypeError: Cannot read property 'error' of undefined
    at /tardis-project-client/lib/appHandler.js:13:12
    at Request._callback (/tardis-project-client/lib/apiClient.js:35:13)
    at self.callback (/tardis-project-client/node_modules/request/request.js:185:22)
    at Request.emit (events.js:305:20)
    at Request.onRequestError (/tardis-project-client/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:305:20)
    at Socket.socketErrorListener (_http_client.js:423:9)
    at Socket.emit (events.js:305:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I'm guessing I either missed something basic as a newbie or version drift in the libraries has broken something in your package. Any idea, please?

**Comment by trraney328** [comment]
what are you going to do with this codes?

**Comment by trraney328** [comment]
#2
